MODEL:
  META_ARCHITECTURE: "ModifiedBlendMask"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_pcpvt_fpn_backbone"
  PVT:
    OUT_FEATURES: ["stage1","stage2", "stage3", "stage4" ]
  FPN:
    IN_FEATURES: ["stage1","stage2", "stage3", "stage4"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  BASIS_MODULE:
    LOSS_ON: True
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: False
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: False
DATASETS:
  TRAIN: ("sem_train",)
  TEST: ("sem_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0075  # Note that RetinaNet uses a different default learning rate
  STEPS: (40000, 60000)
  WARMUP_FACTOR: 0.001
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1
  MAX_ITER: 157613
TEST:
    EVAL_PERIOD: 3000
INPUT:
  MIN_SIZE_TRAIN: (256,256)
  MIN_SIZE_TEST: 256
